# Generated by Django 4.1.1 on 2022-09-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_person_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(help_text='подсказка, если применимо', verbose_name='Описание')),
                ('priority', models.IntegerField(db_index=True, default=1, verbose_name='Приоритет сортировки')),
                ('done', models.DateTimeField(blank=True, null=True, verbose_name='Выполнено')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('deleted', models.DateTimeField(null=True, verbose_name='время удаления')),
            ],
            options={
                'verbose_name': 'Дело',
                'verbose_name_plural': 'Список дел',
                'ordering': ('priority', 'created'),
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
    ]
