# Generated by Django 4.1.1 on 2022-09-29 21:51

from django.db import migrations, models
import core.models


def fill_items(apps, schema):
    Item = apps.get_model('core', 'Item')
    Item.objects.create(name='Купить молока')

def clear_items(apps, schema):
    Item = apps.get_model('core', 'Item')
    Item.objects.filter(name='Купить молока').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_alter_person_options'),
    ]

    operations = [
        migrations.RunPython(code=fill_items, reverse_code=clear_items)
        ]