# Generated by Django 4.1.1 on 2022-10-11 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tag_alter_item_user_item_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemresult',
            name='item',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='ItemResult',
        ),
    ]
